# Generated by Django 5.2.3 on 2025-06-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_lesson_video_description_lesson_video_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('suitable_emotions', models.CharField(help_text='Comma-separated emotions this exercise is good for', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('benefits', models.TextField(help_text='Benefits of this exercise for children with cerebral palsy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('emotion_at_start', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_at_end', models.CharField(blank=True, max_length=50, null=True)),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
