# Generated by Django 5.2.3 on 2025-06-21 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_exercise_userexercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (8am-12pm)'), ('afternoon', 'Afternoon (12pm-4pm)'), ('evening', 'Evening (4pm-8pm)')], max_length=10)),
                ('activity_type', models.CharField(choices=[('lesson', 'Learning Lesson'), ('exercise', 'Physical Exercise'), ('break', 'Rest Break')], max_length=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.exercise')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.lesson')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning_app.activityplan')),
            ],
            options={
                'ordering': ['day_of_week', 'time_slot'],
                'unique_together': {('plan', 'day_of_week', 'time_slot')},
            },
        ),
    ]
